/**
 * PubSystemLib — HospitalityYarn.gs
 *
 * Short hospitality jokes / yarns / surprising true-ish stories for Daily Entry.
 *
 * Picker: stable per calendar day, order shifts each year so Jan 1 ≠ same joke yearly.
 * Top-ups: Script Property HOSPITALITY_YARNS_EXTRA = JSON array of
 *   { "k":"joke"|"funny"|"true", "t":"…" }
 * Merge is built at serve time. Built-in bank is the fallback.
 *
 * Bank sized for ~a year of unique calendar-day picks (year-seed still rotates yearly).
 *
 * clasp (from PubSystemLib folder):
 *   clasp run appendHospitalityYarns --params '[[{"k":"joke","t":"New one here."}]]'
 */

var HOSPITALITY_YARNS_ = [
  { k: 'joke', t: 'A guest asked if the soup of the day was fresh. “It was,” said the chef, “this morning.”' },
  { k: 'joke', t: 'Why did the bartender go to therapy? Too many mixed drinks and not enough neat feelings.' },
  { k: 'joke', t: 'Guest: “Is the fish local?” Waiter: “It is now.”' },
  { k: 'joke', t: 'We don’t have Wi‑Fi passwords. We have table numbers. Same energy, more walking.' },
  { k: 'joke', t: 'A man walked into a bar. Then he walked into another bar. Then he realised he was a glazier.' },
  { k: 'joke', t: 'Kitchen rule: if you can hear the pass, you’re already late.' },
  { k: 'joke', t: '“Can I get that without onions?” Sure. We also do it without a smile if you ask nicely.' },
  { k: 'joke', t: 'The three hardest things: landing a plane, naming a pub quiz team, and finding the spare till roll.' },
  { k: 'joke', t: 'Guest wanted gluten-free water. We poured it carefully into a different glass.' },
  { k: 'joke', t: 'Never trust a quiet Friday. It’s just Monday wearing a better shirt.' },
  { k: 'funny', t: 'A regular once tipped in loyalty points. The till was confused. So were we.' },
  { k: 'funny', t: 'Someone reserved “a quiet table for two.” We gave them the one next to the ice machine. Peak romance.' },
  { k: 'funny', t: 'A delivery driver asked for “the back door.” There were three. He chose the walk-in. Brief, chilly adventure.' },
  { k: 'funny', t: 'New starter polished the brass taps until they squeaked. Guests thought the beer was haunted.' },
  { k: 'funny', t: 'We ran out of lemon wedges. A guest offered a lime “as an upgrade.” Diplomacy at its finest.' },
  { k: 'funny', t: 'The printer jammed mid-rush. Someone shouted “use handwriting!” We briefly considered calligraphy.' },
  { k: 'funny', t: 'A hen party ordered “twelve of whatever’s strongest.” The cocktail menu filed for early retirement.' },
  { k: 'funny', t: 'Found a steak knife in the sugar tin. Investigation ongoing. Suspect: Sunday lunch.' },
  { k: 'funny', t: 'A dog on the patio ordered more attention than the tasting menu. Correct priorities.' },
  { k: 'funny', t: 'Someone paid with a jar of 5p coins “for luck.” The float felt very lucky and very heavy.' },
  { k: 'true', t: 'True-ish: the word “restaurant” comes from French for “restore.” Hence: restore the till roll first.' },
  { k: 'true', t: 'Surprising: during WWII, some pubs kept serving in blackout — quieter rooms, louder gossip.' },
  { k: 'true', t: 'Myth busted: “tip” is not short for To Insure Promptness — that T.I.P. jar story is a later backronym.' },
  { k: 'true', t: 'Odd but true: oyster houses once stayed open late because oysters were street food, not luxury.' },
  { k: 'true', t: 'Pub lore: “mind your own business” may come from tavern tally boards — mind your own tab.' },
  { k: 'true', t: 'Surprising: ice in drinks was a 19th‑century flex. Before that, room-temp beer was the vibe.' },
  { k: 'true', t: 'True: some Victorian pubs had singing licences. Noise complaints are a proud tradition.' },
  { k: 'true', t: 'Industry fact: a “86” means you’re out of it. Origins disputed; results unambiguous.' },
  { k: 'true', t: 'Surprising: tablecloths once signalled class — white linen meant you weren’t eating off a board.' },
  { k: 'true', t: 'Pub history: the “snug” was a private booth — useful for plots, proposals, and quiet arguments.' },
  { k: 'joke', t: 'How do chefs stay calm? They don’t. They just plate it nicer.' },
  { k: 'joke', t: 'I told the wine a joke. It was oaky. The beer laughed louder.' },
  { k: 'joke', t: 'Guest: “What’s your signature dish?” Chef: “Whatever still has stock.”' },
  { k: 'joke', t: 'The till drawer is where dreams go to wait for the float check.' },
  { k: 'joke', t: 'If the coffee machine hisses, it’s not angry. It’s unionising.' },
  { k: 'funny', t: 'A booking note said “allergic to atmosphere.” We dimmed the lights and hoped for the best.' },
  { k: 'funny', t: 'Lost property this week: one glove, two umbrellas, and a sense of portion control.' },
  { k: 'funny', t: 'The fire alarm tested itself during pudding. Guests clapped. We pretended it was theatre.' },
  { k: 'true', t: 'True: Benedictine monks helped spread brewing know-how across Europe. Cheers, lads.' },
  { k: 'true', t: 'Surprising: “last orders” culture is partly a licensing hangover — and a very British countdown.' },
  { k: 'joke', t: 'Why was the napkin always invited back? Great fold. Terrible small talk.' },
  { k: 'funny', t: 'Someone asked for the manager and got the duty manager’s smile. Same person. Different weather.' },
  { k: 'joke', t: 'Break glass in case of emergency. Break service in case of a 40‑top with no deposit.' },
  { k: 'true', t: 'Odd fact: some inns once charged by the “yard of ale.” Hydration, but make it competitive.' },
  { k: 'funny', t: 'The cellar door sticketh. Every pub. Every generation. Character building.' },
  { k: 'joke', t: 'Parallel parking and seating a walk‑in of eight: same heart rate, different sport.' },
  { k: 'true', t: 'Surprising: coffee houses were once called “penny universities” — gossip with a caffeine syllabus.' },
  { k: 'funny', t: 'A review praised our “ambient beeping.” That was the fridge. We’re leaving it in.' },
  { k: 'joke', t: 'The specials board has two sides: what’s on, and what’s emotionally available.' },
  { k: 'funny', t: 'A guest asked for “the usual.” We’d never met. We invented a usual. They’re a regular now.' },
  { k: 'true', t: 'True-ish: “bar” may come from the metal bar that locked the drinks away. Trust issues, historically.' },
  { k: 'joke', t: 'Sommelier voice: “notes of blackberry, oak, and mild panic before Friday service.”' },
  { k: 'funny', t: 'We labelled the clean tea towels “CLEAN.” Someone still used a dirty one. Anthropology continues.' },
  { k: 'joke', t: 'Why did the ice melt at the bar? It couldn’t handle the pressure. Relatable.' },
  { k: 'true', t: 'Surprising: some coaching inns ran on bells and whistles — literal ones — for changeovers.' },
  { k: 'funny', t: 'Stocktake found three “emergency” torches. None had batteries. All had opinions.' },
  { k: 'joke', t: 'A clean pass is a myth, like a quiet bank holiday or a pen that stays on the till.' },
  { k: 'funny', t: 'Someone tried to reserve the car park. We offered a table instead. Negotiation of the year.' },
  { k: 'true', t: 'Odd fact: the ploughman’s lunch was partly a marketing push — cheese and narrative, plated.' },
  { k: 'joke', t: 'Guest scorecard: arrive hungry, leave full, tip like you’ve met the dishwasher.' },
  { k: 'joke', t: 'Guest: “Do you have a kids’ menu?” Us: “Yes — it’s called whatever they don’t drop.”' },
  { k: 'joke', t: 'Why did the lager go to school? It wanted to be cultured. The bitter stayed bitter.' },
  { k: 'joke', t: 'The dishwasher’s love language is rinse aid. Ours is a closed kitchen door.' },
  { k: 'joke', t: '“Is service included?” Only if you include patience, eye contact, and a plan.' },
  { k: 'joke', t: 'How many managers does it take to change a lightbulb? One — and a maintenance ticket from 2019.' },
  { k: 'joke', t: 'We don’t do half-pints of attitude. Full measure only.' },
  { k: 'joke', t: 'Guest wanted their burger “well done.” So did we. Timing disagreed.' },
  { k: 'joke', t: 'The POS system has three modes: working, updating, and revenge.' },
  { k: 'joke', t: 'Why don’t eggs tell jokes in the kitchen? They’d crack under pressure.' },
  { k: 'joke', t: '“Can we split the bill twelve ways?” Sure. Time is also a tip.' },
  { k: 'joke', t: 'The wine list is alphabetical. The chaos is chronological.' },
  { k: 'joke', t: 'I asked for a raise. They raised the music. Close enough.' },
  { k: 'joke', t: 'Guest: “Make it snappy.” Snappy left at 3pm. You’ve got Dave.' },
  { k: 'joke', t: 'Our house special is whatever the delivery actually arrived with.' },
  { k: 'joke', t: 'A ghost walked into a pub. We didn’t charge corkage. Fair’s fair.' },
  { k: 'joke', t: 'Why was the beer flat? It had a long day. Empathy pours.' },
  { k: 'joke', t: '“Is the chicken free-range?” Free as a bird until the ticket hits.' },
  { k: 'joke', t: 'We put the “fun” in “refund policy.” Mostly the “un.”' },
  { k: 'joke', t: 'The salad is dressed better than half the Friday night walk-ins.' },
  { k: 'joke', t: 'Bartender’s motto: shake, strain, smile, survive.' },
  { k: 'joke', t: 'Guest asked for “something local.” We pointed at the puddle in the car park.' },
  { k: 'joke', t: 'Why did the napkin fold? Peer pressure from the cutlery.' },
  { k: 'joke', t: 'Our secret ingredient is salt. And denial. Mostly salt.' },
  { k: 'joke', t: '“Do you take reservations?” Yes. Also apologies, compliments, and cash.' },
  { k: 'joke', t: 'The soup is homemade. The panic is house-made.' },
  { k: 'joke', t: 'A pint of bitter and a pint of mild walked into a bar. Mild got ignored.' },
  { k: 'joke', t: 'We don’t ghost bookings. Bookings ghost us.' },
  { k: 'joke', t: 'Guest: “Surprise me.” Chef: “Surprise — we’re out of that.”' },
  { k: 'joke', t: 'The ice machine’s autobiography: Cold Comfort Farm.' },
  { k: 'joke', t: 'Why did the waiter bring a ladder? High expectations.' },
  { k: 'joke', t: 'Our Wi‑Fi is faster than the sauce. Low bar, still achievement.' },
  { k: 'joke', t: '“Can I speak to the chef?” He’s speaking. It’s called plating.' },
  { k: 'joke', t: 'A clean apron is a temporary lifestyle choice.' },
  { k: 'joke', t: 'The float check is where optimism goes to learn maths.' },
  { k: 'joke', t: 'Guest wanted “whatever’s trending.” We served yesterday’s special with confidence.' },
  { k: 'joke', t: 'Why don’t taps gossip? They’re under pressure to stay sealed.' },
  { k: 'joke', t: 'We offer bottomless coffee. Patience not included.' },
  { k: 'joke', t: 'The dessert trolley has left the station. Walk of shame available.' },
  { k: 'joke', t: '“Is this seat taken?” Emotionally, yes. Physically, all yours.' },
  { k: 'joke', t: 'Our cocktail of the day is named after whoever called in sick.' },
  { k: 'joke', t: 'A bread roll walked into a bar. Soft landing.' },
  { k: 'joke', t: 'Why was the mustard so calm? It was Dijon with life.' },
  { k: 'joke', t: 'We don’t do drama. Drama does us — usually at 7:45.' },
  { k: 'joke', t: 'Guest: “Extra crispy.” Fryer: “Say less.”' },
  { k: 'joke', t: 'The rota is a work of fiction with occasional non-fiction cameos.' },
  { k: 'joke', t: 'How do you know it’s Sunday lunch? The gravy has its own postcode.' },
  { k: 'joke', t: 'Our house wine is honest. Our house music is louder.' },
  { k: 'joke', t: '“Just a quick one.” Famous last orders.' },
  { k: 'joke', t: 'The cutlery drawer knows where everything isn’t.' },
  { k: 'joke', t: 'Guest wanted a “light bite.” We served a heavy suggestion.' },
  { k: 'joke', t: 'Why did the menu blush? Too many specials.' },
  { k: 'joke', t: 'Our gravy boat has sailed. Lifeboats available as sides.' },
  { k: 'joke', t: 'The pepper mill is on a power trip. Literally — it’s electric.' },
  { k: 'joke', t: '“Is the fish sustainably sourced?” The chef is sustainably tired.' },
  { k: 'joke', t: 'A spoon walked into a bar. It stirred things up.' },
  { k: 'joke', t: 'We don’t do rush fees. Rush just happens.' },
  { k: 'joke', t: 'Guest: “Make it fancy.” Us: “Microherb and a prayer.”' },
  { k: 'joke', t: 'The staff room kettle has seen things. It refuses to whistle.' },
  { k: 'joke', t: 'Why was the pie so confident? It had a solid crust plan.' },
  { k: 'joke', t: 'Our loyalty scheme is remembering your name. Premium tier: remembering your dog’s.' },
  { k: 'joke', t: 'A cork popped. So did someone’s patience. Related events.' },
  { k: 'joke', t: '“Can you heat this up?” It’s soup. That’s the entire personality.' },
  { k: 'joke', t: 'The napkin origami class was cancelled. Folds under pressure.' },
  { k: 'joke', t: 'Guest asked for vegan gravy. We delivered with moral support.' },
  { k: 'joke', t: 'Why don’t fridges gossip? Cold shoulders.' },
  { k: 'joke', t: 'Our playlist is curated by whoever got to the Bluetooth first.' },
  { k: 'joke', t: 'A clean glass is a temporary achievement unlocked.' },
  { k: 'joke', t: '“What’s good?” Everything. “What’s ready?” Negotiation.' },
  { k: 'joke', t: 'The bread basket is a trap. Delicious, carb-shaped trap.' },
  { k: 'joke', t: 'We put the “pro” in “improvisation.”' },
  { k: 'joke', t: 'Guest wanted their coffee “as strong as the Wi‑Fi.” Ambitious.' },
  { k: 'joke', t: 'Why did the chef carry a pencil? To draw the line at substitutions.' },
  { k: 'joke', t: 'Our house rule: if it’s on fire, it’s either dramatic or wrong.' },
  { k: 'joke', t: '“Just the bill” is never just the bill. It’s a mini-ceremony.' },
  { k: 'joke', t: 'The sauce reduction reduced us all.' },
  { k: 'joke', t: 'Why was the lager late? It got held up in the lines.' },
  { k: 'joke', t: 'Our dessert menu is short. Like our breaks.' },
  { k: 'joke', t: 'Guest: “Surprise wine.” Sommelier: “Surprise — it’s red.”' },
  { k: 'joke', t: 'The pass is a runway. The tickets are boarding passes.' },
  { k: 'joke', t: 'We don’t lose reservations. They enter witness protection.' },
  { k: 'joke', t: 'Our quiet table is a myth sold by optimists.' },
  { k: 'joke', t: 'A clean cutlery bin is peak civilisation.' },
  { k: 'joke', t: '“Extra sauce” is a personality type. We recognise our people.' },
  { k: 'joke', t: 'The till has favourites. None of them are us.' },
  { k: 'joke', t: 'Why don’t onions cry in the kitchen? They’re already committed.' },
  { k: 'joke', t: 'Our house cocktail: gin, tonic, and a status update.' },
  { k: 'joke', t: 'Guest wanted “no foam.” Barista filed an HR complaint.' },
  { k: 'joke', t: 'The specials board lies only on Tuesdays. And Thursdays.' },
  { k: 'joke', t: 'We plate emotions. Sometimes they run.' },
  { k: 'joke', t: 'Why was the waiter so good at tennis? Great service.' },
  { k: 'joke', t: 'Our emergency plan is “ask the longest-serving person.”' },
  { k: 'joke', t: 'Guest: “Is it spicy?” Chef: “Define your childhood.”' },
  { k: 'joke', t: 'The wine fridge hums showtunes. Or anxiety. Hard to tell.' },
  { k: 'joke', t: 'We don’t do half measures. Except when we do half-pints.' },
  { k: 'joke', t: 'A clean pass window is how you know someone’s on holiday.' },
  { k: 'joke', t: '“Can we get a high chair?” Parenting: the original VIP.' },
  { k: 'joke', t: 'The ice scoop has seniority. Respect the cold chain of command.' },
  { k: 'joke', t: 'Guest wanted “whatever pairs with indecision.” We suggested water first.' },
  { k: 'joke', t: 'Why did the menu go to therapy? Too many attachments.' },
  { k: 'joke', t: 'Our soup of the day is tomorrow’s regret if you skip it.' },
  { k: 'joke', t: 'A clean tea towel is a love language. Rare dialect.' },
  { k: 'joke', t: '“Can we sit anywhere?” Gravity says yes. The floor plan says negotiate.' },
  { k: 'joke', t: 'The coffee machine’s password is “please.” It still refuses some days.' },
  { k: 'joke', t: 'Guest: “Make it Instagram famous.” Us: “We can do edible.”' },
  { k: 'joke', t: 'Why don’t kegs tell secrets? They’re under pressure agreements.' },
  { k: 'joke', t: 'Our house bread is fresh. Our house gossip is fresher.' },
  { k: 'joke', t: 'A napkin folded itself into a swan. Then into a white flag.' },
  { k: 'joke', t: '“Is the kitchen still open?” Define still. Define open. Define hope.' },
  { k: 'joke', t: 'The float is short on miracles tonight.' },
  { k: 'joke', t: 'Guest wanted a quiet celebration. Oxymoron of the evening.' },
  { k: 'joke', t: 'Why was the bartender a great detective? Always reading the room.' },
  { k: 'joke', t: 'Our specials are written in dry-wipe and wet tears.' },
  { k: 'joke', t: '“Just browsing the menu.” Famous last appetisers.' },
  { k: 'joke', t: 'The pass bell is our national anthem.' },
  { k: 'joke', t: 'Guest asked for the manager’s special. Manager’s special is going home.' },
  { k: 'joke', t: 'Why did the chips join a union? They were fed up of being sides.' },
  { k: 'joke', t: 'Our water is filtered. Our excuses are not.' },
  { k: 'joke', t: 'A clean bar top is a temporary art installation.' },
  { k: 'joke', t: '“Can I get that to go?” Emotionally, we’re all to-go by 11.' },
  { k: 'joke', t: 'The rota app knows too much.' },
  { k: 'joke', t: 'Guest: “Surprise me with dessert.” Us: “Surprise — it’s sticky toffee.”' },
  { k: 'joke', t: 'Why don’t wine bottles gossip? They’re corked.' },
  { k: 'joke', t: '“Is service slow?” No — the kitchen is thorough. And also slow.' },
  { k: 'joke', t: 'The dishwasher’s cycle is longer than some relationships.' },
  { k: 'joke', t: 'Guest wanted mild spice. We delivered mild disappointment carefully.' },
  { k: 'joke', t: 'Why was the lager so chill? Natural carbonation of temperament.' },
  { k: 'joke', t: 'Our house rule: count the floats twice, the compliments once.' },
  { k: 'joke', t: 'A clean apron means the shift hasn’t started.' },
  { k: 'joke', t: '“What’s the Wi‑Fi?” Same as last week. And the week before.' },
  { k: 'joke', t: 'The sauce is reduced. So is our willpower.' },
  { k: 'joke', t: 'Guest asked for bottomless chips. We offered bottomless honesty.' },
  { k: 'joke', t: 'Why did the waiter carry a torch? For the cellar. And metaphorically.' },
  { k: 'joke', t: 'Our dessert wine has notes of “yes please.”' },
  { k: 'joke', t: '“Can we move tables?” Sure. Bring the chaos with you.' },
  { k: 'joke', t: 'The till roll’s autobiography: Endless.' },
  { k: 'joke', t: 'Guest wanted their steak “pink but brown.” Art school special.' },
  { k: 'joke', t: 'Why don’t ice cubes last? Pressure of nightlife.' },
  { k: 'joke', t: 'Our quiet night playlist is the walk-in’s theme tune.' },
  { k: 'joke', t: 'A clean glass rack is how you know the delivery’s late.' },
  { k: 'joke', t: '“Just a soft drink.” Soft launch for a long night.' },
  { k: 'joke', t: 'The pepper is cracked. So are we. Related.' },
  { k: 'joke', t: 'How do bartenders stay cool? Draft.' },
  { k: 'joke', t: 'Guest: “Is the bread free?” Nothing’s free after the butter arrives.' },
  { k: 'joke', t: 'Why did the gravy apply for a passport? It wanted to go places.' },
  { k: 'joke', t: '“Any allergies?” “Yes — waiting.” Noted.' },
  { k: 'joke', t: 'The special is surprise. The surprise is we’re out of it.' },
  { k: 'joke', t: 'Why don’t chefs play cards in service? Too many deals already.' },
  { k: 'joke', t: 'Our coffee is fair trade. Our breaks are unfair.' },
  { k: 'joke', t: 'Guest asked for the wine “with least maths.” House pour it is.' },
  { k: 'joke', t: 'We don’t upsell. We gently narrate better options.' },
  { k: 'joke', t: 'Why was the kitchen so quiet? It wasn’t. Ever.' },
  { k: 'joke', t: 'Our house rule: if you can lean, you can clean — and then lean again.' },
  { k: 'joke', t: 'Guest: “What’s popular?” Us: “Leaving happy.”' },
  { k: 'joke', t: 'The float bag has trust issues. Fair.' },
  { k: 'joke', t: 'Why did the lemon wedge go to school? To become well-rounded.' },
  { k: 'joke', t: '“Can I get a tall glass?” Personality or vessel — clarify.' },
  { k: 'joke', t: 'The pass ticket printer has trust issues with Wi‑Fi.' },
  { k: 'joke', t: 'Guest wanted “farm to table.” We pointed at the car park puddle farm.' },
  { k: 'joke', t: 'Why don’t sauces gossip? They’re reduced to essentials.' },
  { k: 'joke', t: 'Our dessert of the day is whatever still has dignity.' },
  { k: 'joke', t: '“Just water.” Hydration: the original soft launch.' },
  { k: 'joke', t: 'The beer pump badges are our trading cards.' },
  { k: 'joke', t: 'Guest: “Make it Instagrammable.” Chef: “Make it edible first.”' },
  { k: 'joke', t: 'Why was the ice so popular? It knew how to chill.' },
  { k: 'joke', t: '“Is the fish off?” Only if the ticket says 86.' },
  { k: 'joke', t: 'The till drawer sticks when the universe needs drama.' },
  { k: 'joke', t: 'Guest asked for gluten-free gravy. We checked the flour treaty.' },
  { k: 'joke', t: 'Why did the waiter carry a notebook? Plot twists mid-order.' },
  { k: 'joke', t: 'Our quiet corner has excellent acoustics for complaints.' },
  { k: 'joke', t: '“What’s the soup?” Liquid hope with croutons.' },
  { k: 'joke', t: 'Guest wanted their cocktail “not too cocktaily.” Water with garnish.' },
  { k: 'joke', t: 'Why don’t menus lie? They omit. Different skill.' },
  { k: 'joke', t: 'Our staff meal is a mystery box with carbs.' },
  { k: 'joke', t: '“Can we get the bill?” The bill was waiting. Patiently. Judgementally.' },
  { k: 'joke', t: 'The pepper mill is the loudest person at the table.' },
  { k: 'joke', t: 'Guest: “Surprise starter.” Us: “Soup. Always soup.”' },
  { k: 'joke', t: 'Why was the bitter so wise? Years in the cellar.' },
  { k: 'joke', t: 'A clean glass is how you know the glasswasher is bribed correctly.' },
  { k: 'joke', t: '“Any specials?” Emotionally, no. Culinary, yes.' },
  { k: 'joke', t: 'Guest wanted bottomless brunch. We offered bottomless patience until noon.' },
  { k: 'joke', t: 'Why did the napkin apply for a job? It wanted to fold into something greater.' },
  { k: 'joke', t: 'Our Wi‑Fi name is longer than some guest attentions.' },
  { k: 'joke', t: '“Just the one.” Famous opening line.' },
  { k: 'joke', t: 'Guest asked if we do bottomless coffee. We do bottomless ambition.' },
  { k: 'joke', t: 'Why don’t dishwashers dream? They’re always in hot water.' },
  { k: 'joke', t: '“What’s good tonight?” Everything we still have.' },
  { k: 'joke', t: 'The float check is cardio.' },
  { k: 'joke', t: 'Guest: “Make it quick.” Universe: “Make it interesting.”' },
  { k: 'joke', t: 'Why did the chips go to therapy? They felt like a side character.' },
  { k: 'joke', t: 'Our dessert trolley is theoretical physics.' },
  { k: 'joke', t: '“Is service included?” Smiles are. Miracles are à la carte.' },
  { k: 'joke', t: 'The POS update always lands mid-rush. Always.' },
  { k: 'joke', t: 'Guest wanted their steak blue. We served rare courage.' },
  { k: 'joke', t: 'Why was the lager invited everywhere? It was always draftable.' },
  { k: 'joke', t: 'Our house rule: tip the dishwasher in your heart.' },
  { k: 'joke', t: '“Can I speak to someone in charge?” We’re all in charge of the ice.' },
  { k: 'joke', t: 'The kettle in the staff room is unionised.' },
  { k: 'joke', t: 'Why don’t bar stools gossip? They support everyone equally.' },
  { k: 'joke', t: 'Our specials board has commitment issues.' },
  { k: 'joke', t: '“Just browsing.” The chips heard that.' },
  { k: 'joke', t: 'The till roll ends only when you need it most.' },
  { k: 'joke', t: 'Guest: “Is it organic?” The panic is free-range.' },
  { k: 'joke', t: 'Why did the gravy thicken? Character development.' },
  { k: 'joke', t: 'Our coffee machine has more moods than the weather app.' },
  { k: 'joke', t: '“Any tables?” Define table. Define available. Define optimism.' },
  { k: 'joke', t: 'Guest wanted a tasting flight of crisps. Valid.' },
  { k: 'joke', t: 'Why don’t ice machines retire? Cold ambition.' },
  { k: 'joke', t: 'Our house wine pairs with decisions deferred.' },
  { k: 'joke', t: '“What’s the Wi‑Fi password?” Patience.' },
  { k: 'joke', t: 'The cellar steps build character and calves.' },
  { k: 'joke', t: 'Guest: “Surprise me.” Us: “Card machine’s working.”' },
  { k: 'joke', t: 'Why was the mustard invited to parties? It knew how to cut through.' },
  { k: 'joke', t: 'Our playlist is 40% bangers, 60% “who connected?”' },
  { k: 'joke', t: '“Can we sit outside?” Bring a coat and a subplot.' },
  { k: 'joke', t: 'The float is a democracy of coins.' },
  { k: 'joke', t: 'Guest asked for oat milk stout. Modern classic pending.' },
  { k: 'joke', t: 'Why did the menu go viral? It didn’t. The gravy did.' },
  { k: 'joke', t: 'Our house soup is thicker than the plot of Friday night.' },
  { k: 'joke', t: '“Just a half.” Soft launch energy.' },
  { k: 'joke', t: 'Guest wanted gluten-free water again. We have a glass for that.' },
  { k: 'joke', t: 'Why don’t chefs sleep? The mise doesn’t.' },
  { k: 'joke', t: 'A clean glass rack sings in the key of ready.' },
  { k: 'joke', t: '“Is the kitchen open?” Spiritually, always. Practically, check the board.' },
  { k: 'joke', t: 'Guest: “Make it fancy but casual.” Understood: herbs and denim vibes.' },
  { k: 'joke', t: 'Why was the ice melted by politics? Too much heat in the room.' },
  { k: 'joke', t: '“Any allergies to atmosphere?” Dimmer switch deployed.' },
  { k: 'joke', t: 'The till drawer is where pens go to die.' },
  { k: 'joke', t: 'Guest asked for the manager’s favourite table. It’s the office chair.' },
  { k: 'joke', t: 'Why don’t wine lists blink? Too many notes.' },
  { k: 'joke', t: '“What’s popular?” Leaving with a plan for next week.' },
  { k: 'joke', t: 'The beer lines have opinions. Listen carefully.' },
  { k: 'joke', t: 'Guest wanted their coffee as strong as last Friday. Ambitious archaeology.' },
  { k: 'joke', t: 'Why did the waiter bring two pens? Redundancy planning.' },
  { k: 'joke', t: 'Our quiet night is a rumour started by Monday.' },
  { k: 'joke', t: '“Can I get that without waiting?” You can get that without magic.' },
  { k: 'joke', t: 'Guest: “Surprise wine pairing.” Us: “It pairs with saying yes.”' },
  { k: 'joke', t: 'Why don’t kegs roll uphill? Gravity and health & safety.' },
  { k: 'joke', t: '“Just the bill when you can.” When you can is a lifestyle.' },
  { k: 'joke', t: 'Guest asked if dogs get water. Dogs get VIP water.' },
  { k: 'joke', t: 'Why was the bitter invited to the meeting? It brought balance.' },
  { k: 'joke', t: 'Our specials are a suggestion and a negotiation.' },
  { k: 'joke', t: '“Is service slow on purpose?” No. The universe is collaborative.' },
  { k: 'joke', t: 'The POS has three languages: beep, error, spite.' },
  { k: 'joke', t: 'Why don’t dishwashers join bands? Always stuck in a cycle.' },
  { k: 'joke', t: 'Our house rule: if the ice is low, the night is high.' },
  { k: 'joke', t: '“What’s the soup of the day?” Whatever survived stocktake.' },
  { k: 'joke', t: 'Guest: “Make it Instagram and edible.” Dual KPI accepted.' },
  { k: 'joke', t: 'Why did the lemon blush? It saw the gin.' },
  { k: 'joke', t: '“Can we split starters?” Yes. Also the arguments.' },
  { k: 'joke', t: 'Guest asked for a quiet table by the ice machine. Classic.' },
  { k: 'joke', t: 'Why don’t bar mats retire? They’re steeped in history.' },
  { k: 'joke', t: 'Our house wine has notes of “another bottle?”' },
  { k: 'joke', t: '“Any tables for walk-ins?” Walk-ins invent tables.' },
  { k: 'joke', t: 'Guest wanted bottomless patience. Limited stock.' },
  { k: 'joke', t: 'Why was the gravy late? Thick plot.' },
  { k: 'joke', t: '“Just browsing the desserts.” The sticky toffee heard that.' },
  { k: 'joke', t: 'The pass ticket is a tiny contract with destiny.' },
  { k: 'joke', t: 'Guest: “Is it local?” Define local. Define still available.' },
  { k: 'joke', t: 'Why don’t ice scoops gossip? Cold professionalism.' },
  { k: 'joke', t: '“What’s good?” The dog on the patio. Also the pie.' },
  { k: 'joke', t: 'Guest asked for the usual. We delivered continuity.' },
  { k: 'joke', t: 'Why did the chips feel validated? Someone ordered them as a main.' },
  { k: 'joke', t: '“Can I get a high chair and a low bill?” Parenting goals.' },
  { k: 'joke', t: 'Guest wanted their steak well done and juicy. Physics optional.' },
  { k: 'joke', t: 'Why don’t menus sweat? Laminated calm.' },
  { k: 'joke', t: '“Just a soft drink and a long story.” Classic cover charge.' },
  { k: 'joke', t: 'Guest: “Surprise me carefully.” Oxymoron accepted.' },
  { k: 'joke', t: 'Why was the waiter great at chess? Thinking two tables ahead.' },
  { k: 'joke', t: '“Is the kitchen still open?” Hope is open. Tickets may vary.' },
  { k: 'joke', t: 'Guest asked for gluten-free everything. We gluten-free’d the panic.' },
  { k: 'joke', t: 'Why don’t chefs count sheep? They count tickets.' },
  { k: 'joke', t: '“Any allergies?” “Only to small portions.” Noted with respect.' },
  { k: 'joke', t: 'Guest wanted a light bite after a heavy week. Understood.' },
  { k: 'joke', t: 'Why did the mustard stay calm? Training.' },
  { k: 'joke', t: '“Can we sit anywhere?” Anywhere includes the philosophical void.' },
  { k: 'joke', t: 'Guest: “Make it snappy but perfect.” Dual mandate logged.' },
  { k: 'joke', t: 'Why don’t wine fridges sleep? Humming therapy.' },
  { k: 'joke', t: '“What’s the Wi‑Fi?” Same as the last polite sigh.' },
  { k: 'joke', t: 'Guest asked for oat milk in the gravy. We opened a summit.' },
  { k: 'joke', t: 'Why was the lager always invited? Draft personality.' },
  { k: 'joke', t: '“Just the one” lasted three. Classic trilogy.' },
  { k: 'joke', t: 'Guest wanted Instagram lighting. We offered overhead honesty.' },
  { k: 'joke', t: 'Why don’t bar stools complain? They support the arts.' },
  { k: 'joke', t: '“Can I speak to the chef?” He’s speaking in garnish.' },
  { k: 'joke', t: 'Guest: “Surprise dessert.” Us: “It’s sticky. Always.”' },
  { k: 'joke', t: 'Why did the gravy need a passport? International appeal.' },
  { k: 'joke', t: '“Any tables outside?” Bring layers and narrative.' },
  { k: 'joke', t: 'Guest asked if the fish was local. Local to the plate now.' },
  { k: 'joke', t: 'Why don’t dishwashers write memoirs? Too steamy.' },
  { k: 'joke', t: 'Our house rule: tip with dignity, order with clarity.' },
  { k: 'joke', t: '“What’s popular tonight?” Leaving before the dishwasher breaks.' },
  { k: 'joke', t: 'Guest wanted mild spice and wild vibes. Possible.' },
  { k: 'joke', t: 'Why was the bitter so reliable? Consistent character.' },
  { k: 'joke', t: '“Is service included?” Smiles yes. Telepathy no.' },
  { k: 'joke', t: 'Guest asked for a quiet celebration with twelve people. Bold.' },
  { k: 'joke', t: 'Why don’t ice machines quit? Union of cold.' },
  { k: 'joke', t: '“Just browsing.” The specials board felt seen.' },
  { k: 'joke', t: 'Guest: “Make it fancy.” Microherbs deployed.' },
  { k: 'joke', t: 'Why did the lemon go to the bar? Gin needed a friend.' },
  { k: 'joke', t: 'Our house soup is a hug with a ladle.' },
  { k: 'joke', t: '“Can we move?” Yes. Bring the crumbs of destiny.' },
  { k: 'joke', t: 'Guest wanted bottomless chips and finite time. Tension.' },
  { k: 'joke', t: 'Why don’t chefs play hide and seek? The tickets find them.' },
  { k: 'joke', t: '“Any soft drinks with opinions?” All of them.' },
  { k: 'joke', t: 'Guest asked for the manager’s smile. Weather permitting.' },
  { k: 'joke', t: 'Why was the mustard so sharp? Practice.' },
  { k: 'joke', t: '“Just the bill.” Ceremony begins.' },
  { k: 'joke', t: 'Guest wanted their coffee stronger than the Wi‑Fi. Quest accepted.' },
  { k: 'joke', t: 'Why don’t menus blink first? Laminated nerve.' },
  { k: 'joke', t: '“What’s good?” The pie. Always check the pie.' },
  { k: 'joke', t: 'Guest: “Surprise me.” Us: “Card machine works.”' },
  { k: 'joke', t: 'Why did the chips unionise? Side-character energy.' },
  { k: 'joke', t: '“Can I get that without drama?” We can try.' },
  { k: 'joke', t: 'Guest asked for gluten-free panic. We ran out.' },
  { k: 'joke', t: 'Why don’t bar mats dry fully? Emotional residue.' },
  { k: 'joke', t: '“Any tables?” Hope inventory updating…' },
  { k: 'joke', t: 'Guest wanted a light bite and a heavy pour. Balance.' },
  { k: 'joke', t: 'Why was the waiter ahead? Two tables of foresight.' },
  { k: 'joke', t: '“Is the kitchen open spiritually?” Always.' },
  { k: 'joke', t: 'Guest: “Make it snappy.” Snappy’s off. Dave’s on.' },
  { k: 'joke', t: 'Why don’t wine bottles text back? Corked signal.' },
  { k: 'joke', t: '“What’s the soup?” Liquid continuity.' },
  { k: 'joke', t: 'Guest asked for the usual we invented last week. Canon.' },
  { k: 'joke', t: 'Why did the gravy thicken overnight? Plot armour.' },
  { k: 'joke', t: '“Just a half and a plan.” Respect.' },
  { k: 'joke', t: 'Guest wanted Instagram and gravy. Dual success path.' },
  { k: 'joke', t: 'Why don’t ice scoops retire early? Cold calling.' },
  { k: 'joke', t: '“Can we sit by the window?” Windows are democratic.' },
  { k: 'joke', t: 'Guest asked if dogs tip. Dogs tip joy.' },
  { k: 'joke', t: 'Why was the bitter invited back? Consistent notes.' },
  { k: 'joke', t: '“Any allergies to waiting?” Common. Untreatable.' },
  { k: 'joke', t: 'Guest: “Surprise starter.” Soup. Continuity.' },
  { k: 'joke', t: 'Why don’t dishwashers ghost? Stuck in cycle.' },
  { k: 'joke', t: '“What’s popular?” The dog. And the pie.' },
  { k: 'joke', t: 'Guest wanted mild everything except the gossip.' },
  { k: 'joke', t: 'Why did the lemon join gin? Chemistry.' },
  { k: 'joke', t: '“Can I get a tall story and a short bill?” Classic ask.' },
  { k: 'joke', t: 'Guest asked for oat milk diplomacy. Summit held.' },
  { k: 'joke', t: 'Why don’t chefs count sheep at night? Tickets bleat louder.' },
  { k: 'joke', t: '“Just browsing desserts.” Sticky toffee activated.' },
  { k: 'joke', t: 'Guest wanted physics-defying steak. Noted.' },
  { k: 'joke', t: 'Why was the lager draftable? Personality.' },
  { k: 'joke', t: '“Is service telepathic?” Not yet. Tip anyway.' },
  { k: 'joke', t: 'Guest: “Make it perfect quickly.” Logged as epic.' },
  { k: 'joke', t: 'Why don’t bar stools lean in? They already support.' },
  { k: 'joke', t: '“Any tables for destiny?” Check walk-ins.' },
  { k: 'joke', t: 'Guest wanted bottomless time. Limited licence.' },
  { k: 'joke', t: 'Why don’t menus sweat the small stuff? Laminate.' },
  { k: 'joke', t: '“Can we split everything including opinions?” Yes.' },
  { k: 'joke', t: 'Guest wanted local fish energy. Plate-local achieved.' },
  { k: 'joke', t: 'Why did the chips become a main? Representation.' },
  { k: 'joke', t: '“What’s good?” Leaving with next-week plans.' },
  { k: 'joke', t: 'Guest asked for the manager’s weather. Variable.' },
  { k: 'joke', t: 'Why don’t ice machines strike? They’re solid.' },
  { k: 'joke', t: '“Just the ceremony of the bill.” Begin.' },
  { k: 'joke', t: 'Guest wanted dual KPI plates. Edible plus photogenic.' },
  { k: 'joke', t: 'Why was the mustard trained? Calm under roast.' },
  { k: 'joke', t: '“Any soft opinions?” All drinks have them.' },
  { k: 'joke', t: 'Guest: “Surprise carefully.” Accepted.' },
  { k: 'joke', t: 'Why don’t wine fridges sleep in? Hum shifts.' },
  { k: 'joke', t: '“Can we move with destiny crumbs?” Yes.' },
  { k: 'joke', t: 'Guest asked for Wi‑Fi-strength coffee. Quest.' },
  { k: 'joke', t: 'Why don’t bar mats fully dry? Lore stains.' },
  { k: 'joke', t: '“Any hope inventory?” Updating…' },
  { k: 'joke', t: 'Guest wanted heavy pour, light bite. Yin yang.' },
  { k: 'joke', t: 'Why was foresight two tables deep? Practice.' },
  { k: 'joke', t: '“Spiritually open kitchen?” Affirmative.' },
  { k: 'joke', t: 'Guest wanted a tasting of house patience. Sold out.' },
  { k: 'joke', t: 'Why did the pie win the argument? Solid grounding.' },
  { k: 'joke', t: '“Can the dog have a seat?” The dog already chairs the meeting.' },
  { k: 'joke', t: 'Guest asked for less ice and more drama. Partial delivery.' },
  { k: 'joke', t: 'Why don’t tea towels retire? Spin cycle of life.' },
  { k: 'joke', t: '“What’s the manager’s favourite?” Sitting down.' },
  { k: 'joke', t: 'Guest wanted a round of applause. We poured a round instead.' },
  { k: 'joke', t: 'Why was the cellar so confident? It had depth.' },
  { k: 'joke', t: '“Just one more soft launch.” Famous last soft drink.' },
  { k: 'joke', t: 'Guest asked if the gravy was homemade. The panic was too.' },
  { k: 'joke', t: 'Why don’t pump clips lie? They clip the truth in place.' },
  { k: 'joke', t: '“Any chance of a miracle?” Check the ice first.' },
  { k: 'joke', t: 'Guest wanted the table with best acoustics for secrets. Snug adjacent.' },
  { k: 'joke', t: 'Why did the napkin surrender then soar? Character arc.' },
  { k: 'joke', t: '“Can we book the vibe?” Vibes are walk-up only.' },
  { k: 'joke', t: 'Guest asked for a non-alcoholic adventure. Mocktail cartography ensued.' },
  { k: 'joke', t: 'Why don’t floats balance themselves? They enjoy the attention.' },
  { k: 'joke', t: '“What’s cooking?” Stress and something delicious.' },
  { k: 'joke', t: 'Guest wanted fewer choices and more chips. Leadership quality.' },
  { k: 'joke', t: 'Why was Sunday lunch late? Gravy traffic.' },
  { k: 'joke', t: '“Just the crossword and a pint.” Peak civilisation.' },
  { k: 'joke', t: 'Guest asked if we compost ambition. Daily.' },
  { k: 'joke', t: 'Why don’t specials last forever? Dry-wipe destiny.' },
  { k: 'joke', t: '“Can I get the Wi‑Fi and a plot twist?” Router first.' },
  { k: 'joke', t: 'Guest wanted their bill split by astrology. Denied kindly.' },
  { k: 'joke', t: 'Why did the bar mat survive Saturday? Steeped resilience.' },
  { k: 'joke', t: '“Any seats near hope?” Middle of the room.' },
  { k: 'joke', t: 'Guest asked for the quietest loud table. Assigned scientifically.' },
  { k: 'joke', t: 'Why don’t gravy boats sink? Thick buoyancy.' },
  { k: 'joke', t: '“What’s the secret?” Salt, timing, and not telling.' },
  { k: 'joke', t: 'Guest wanted a free pep talk with the peppermill. Provided.' },
  { k: 'joke', t: 'Why was the till so dramatic? Cliffhangers sell.' },
  { k: 'joke', t: '“Just browsing the specials.” They browsed back.' },
  { k: 'joke', t: 'Guest asked for a side of clarity. We plated honesty.' },
  { k: 'joke', t: 'Why don’t cellar steps get easier? Character DLC.' },
  { k: 'joke', t: '“Can the quiz machine join our team?” It already beat you.' },
  { k: 'joke', t: 'Guest wanted less foam, more feelings. Flat white diplomacy.' },
  { k: 'joke', t: 'Why did the house wine keep getting invited? It said yes.' },
  { k: 'joke', t: '“Any tables with character?” All of them. Some have drafts.' },
  { k: 'joke', t: 'Guest asked for the dessert that forgives Mondays. Sticky toffee.' },
  { k: 'joke', t: 'Why don’t pen shortages end? Pens prefer pockets.' },
  { k: 'joke', t: '“What’s on?” Music, tickets, and mild chaos.' },
  { k: 'joke', t: 'Guest wanted a tasting flight of atmospheres. Dimmer tour arranged.' },
  { k: 'joke', t: 'Why was the ice VIP? Scarcity pricing of cubes.' },
  { k: 'joke', t: '“Just a half of whatever’s kind.” Soft landing accepted.' },
  { k: 'funny', t: 'A guest asked if the roast was “Instagrammable.” We said yes if you like brown.' },
  { k: 'funny', t: 'Someone brought their own placemat. We respected the commitment.' },
  { k: 'funny', t: 'The quiz machine beat a team called “We’ve Got This.” They did not.' },
  { k: 'funny', t: 'A booking for “two quiet drinkers” became twelve loud ones. Evolution.' },
  { k: 'funny', t: 'We found a left shoe in the beer garden. Right shoe still at large.' },
  { k: 'funny', t: 'A guest rate-limited our Wi‑Fi by livestreaming the chips. Fair.' },
  { k: 'funny', t: 'New glasswasher: whisper quiet. Old one: heavy metal tribute.' },
  { k: 'funny', t: 'Someone ordered “a pint of whatever’s local and apologetic.” We understood.' },
  { k: 'funny', t: 'The thermostat war ended in a draw. Jumpers and fans both deployed.' },
  { k: 'funny', t: 'A regular brought cake for staff. We briefly trusted humanity again.' },
  { k: 'funny', t: 'Lost and found now includes a monocle. We are not asking questions.' },
  { k: 'funny', t: 'The smoke alarm mistook toast for a crisis. Toast was, in fairness, ambitious.' },
  { k: 'funny', t: 'Someone asked for the wine “not too winey.” We poured water with theatre.' },
  { k: 'funny', t: 'A hen do arrived early. The fridge whimpered.' },
  { k: 'funny', t: 'Someone tipped in foreign coins. The float is now cosmopolitan.' },
  { k: 'funny', t: 'The piano in the corner hasn’t been tuned since Brexit. Guests still try.' },
  { k: 'funny', t: 'Someone requested “ambient lighting.” We turned off the kitchen strip light. Close.' },
  { k: 'funny', t: 'A delivery was left “by the bins.” The bins were thrilled. We were less so.' },
  { k: 'funny', t: 'We labelled the sauce bottles. Labels peeled. Chaos restored.' },
  { k: 'funny', t: 'A dog sat more politely than its owner. We almost gave it a menu.' },
  { k: 'funny', t: 'The fire exit got blocked by a buggy. Parenting vs licensing: discuss.' },
  { k: 'funny', t: 'Someone asked if we do bottomless brunch. We do bottomless patience until noon.' },
  { k: 'funny', t: 'A guest “just popped in.” Three hours and a cheese board later…' },
  { k: 'funny', t: 'The cellar flood was an inch deep and a novel long.' },
  { k: 'funny', t: 'We put up a “quiet corner” sign. It became the loudest corner. Irony tax.' },
  { k: 'funny', t: 'A booking note: “celebrating nothing.” We celebrated with chips.' },
  { k: 'funny', t: 'The till roll ran out mid-card. Guests clapped like it was intentional.' },
  { k: 'funny', t: 'Someone wanted their steak “blue but cooked.” Philosophy hour.' },
  { k: 'funny', t: 'We found a name badge from 2014. The name still works here. Continuity.' },
  { k: 'funny', t: 'A guest asked for the manager’s favourite. Manager’s favourite is sitting down.' },
  { k: 'funny', t: 'The patio heaters outnumbered the guests. Winter democracy.' },
  { k: 'funny', t: 'Someone reserved “near the window.” All windows were near themselves. Solved.' },
  { k: 'funny', t: 'A wedding party practiced speeches at the bar. We practiced not crying.' },
  { k: 'funny', t: 'The ice ran out. Cubes became a controlled substance.' },
  { k: 'funny', t: 'A review said “authentic pub smell.” We took it as a compliment. Mostly.' },
  { k: 'funny', t: 'Someone tried to pay with a screenshot of a bank balance. Bold strategy.' },
  { k: 'funny', t: 'The staff meal was soup. The staff meal is always soup. Tradition.' },
  { k: 'funny', t: 'A guest asked if the beer was “artisanal.” The cellar shrugged artisanally.' },
  { k: 'funny', t: 'We hosted a silent disco. The kitchen was not silent. Never is.' },
  { k: 'funny', t: 'Someone left a half-finished crossword. We finished it wrong on purpose.' },
  { k: 'funny', t: 'The coat hooks filled up. So did the floor. Gravity: undefeated.' },
  { k: 'funny', t: 'A booking said “no drama.” Then arrived with a cake and an announcement.' },
  { k: 'funny', t: 'We trained a new starter on the till. The till trained back.' },
  { k: 'funny', t: 'Someone asked for “the table with the best vibe.” We spun the lazy Susan of destiny.' },
  { k: 'funny', t: 'The glasswasher sang a high C. Opera night, unintended.' },
  { k: 'funny', t: 'A guest wanted oat milk in their stout. We filed it under modern art.' },
  { k: 'funny', t: 'Lost property: one sock, one earring, zero matching pairs. As designed.' },
  { k: 'funny', t: 'We put “please wait to be seated” on the board. Guests seated themselves. Literacy optional.' },
  { k: 'funny', t: 'Someone asked if we take crypto. We take compliments and card.' },
  { k: 'funny', t: 'A guest brought a portable fan. Microclimate VIP.' },
  { k: 'funny', t: 'We found a bow tie in lost property. Fancy night, unclear owner.' },
  { k: 'funny', t: 'Someone reserved “away from children.” Sat next to a birthday. Fate.' },
  { k: 'funny', t: 'The blackboard eraser vanished. Chalk crime wave continues.' },
  { k: 'funny', t: 'A regular’s dog knows more staff names than the new starter.' },
  { k: 'funny', t: 'We hosted a wake and a hen do same night. Emotional range: advanced.' },
  { k: 'funny', t: 'Someone asked for the wine “with least decisions.” House white it is.' },
  { k: 'funny', t: 'The patio cushions migrated indoors. Seasonal refugees.' },
  { k: 'funny', t: 'A guest tipped in scratch cards. Luck transferred sideways.' },
  { k: 'funny', t: 'We labelled the hot sauce “HOT.” Guests still asked. Science.' },
  { k: 'funny', t: 'Someone practiced a best-man speech at the bar. We became the rehearsal room.' },
  { k: 'funny', t: 'The glasswasher door is a portal to another dimension of steam.' },
  { k: 'funny', t: 'A booking note: “proposal possible.” Kitchen plated nerves.' },
  { k: 'funny', t: 'We ran out of tonic. Creativity and lemonade entered chat.' },
  { k: 'funny', t: 'Someone asked if the fireplace works. Emotionally, yes.' },
  { k: 'funny', t: 'The staff meal lottery: pasta, pasta, or pasta with opinions.' },
  { k: 'funny', t: 'A guest left a five-star review for the dog bowl. Peak.' },
  { k: 'funny', t: 'We put “reserved” signs on calm. Calm left anyway.' },
  { k: 'funny', t: 'Someone ordered a round for the kitchen. Heroes recognised.' },
  { k: 'funny', t: 'The beer garden fairy lights outlasted three managers.' },
  { k: 'funny', t: 'A quiz team called “Last Minute” arrived last minute. Branding.' },
  { k: 'funny', t: 'We found a map of the cellar drawn by a previous cellar person. Treasure.' },
  { k: 'funny', t: 'Someone asked for oat milk in everything. Oat supremacy achieved.' },
  { k: 'funny', t: 'The coat hooks invented new physics on busy Fridays.' },
  { k: 'funny', t: 'Someone brought their own placemat again. Sequel energy.' },
  { k: 'funny', t: 'We trained “smile with eyes” during mask years. Skill retained.' },
  { k: 'funny', t: 'Someone reserved the snug for “strategic planning.” Snacks approved.' },
  { k: 'funny', t: 'The ice machine’s filter change is a bank holiday for cubes.' },
  { k: 'funny', t: 'A lost umbrella farm grows by the door every November.' },
  { k: 'funny', t: 'Someone asked if we compost. We compost ambition daily.' },
  { k: 'funny', t: 'A guest brought a measuring tape for the burger. Science night.' },
  { k: 'funny', t: 'The Christmas lights stayed up until March. Festive endurance.' },
  { k: 'funny', t: 'Someone reserved under “Table for one and a laptop.” We nodded sagely.' },
  { k: 'funny', t: 'We found a rubber duck in the ice well. Leadership meeting ensued.' },
  { k: 'funny', t: 'A booking note: “allergic to loud cutlery.” We tiptoed the teaspoons.' },
  { k: 'funny', t: 'The beer garden umbrella inverted. Modern sculpture, briefly.' },
  { k: 'funny', t: 'Someone paid exactly to the penny from a tiny purse. Legendary float.' },
  { k: 'funny', t: 'We hosted a book club. They drank more than they read. Literature wins.' },
  { k: 'funny', t: 'A guest asked for the Wi‑Fi and the meaning of life. Router first.' },
  { k: 'funny', t: 'The cellar steps counted themselves. Still seventeen. Still steep.' },
  { k: 'funny', t: 'Someone tried to tip in gift cards. Creative capitalism.' },
  { k: 'funny', t: 'We put flowers on the tables. A dog ate one. Nature documentary.' },
  { k: 'funny', t: 'A hen party brought a sash for the landlord. He wore it. Icon.' },
  { k: 'funny', t: 'The printer jam coincided with a proposal. Romance and receipts.' },
  { k: 'funny', t: 'Someone asked for the manager’s table. Manager’s table is the office floor.' },
  { k: 'funny', t: 'We ran out of straws. Guests innovated with spaghetti. Mixed reviews.' },
  { k: 'funny', t: 'A regular corrected our blackboard spelling. We hired them morally.' },
  { k: 'funny', t: 'The patio ashtray became a sculpture garden of good intentions.' },
  { k: 'funny', t: 'Someone ordered “one of everything small.” The kitchen filed for mercy.' },
  { k: 'funny', t: 'We found a love letter in a menu. Plot twist: it was a complaint.' },
  { k: 'funny', t: 'A guest rated the toilets five stars. Peak hospitality metrics.' },
  { k: 'funny', t: 'The quiz host lost the answers. Improvised truth. Chaos points.' },
  { k: 'funny', t: 'Someone brought their own ketchup. We saluted the commitment.' },
  { k: 'funny', t: 'We labelled allergens in giant font. Guests still asked. Literacy is a journey.' },
  { k: 'funny', t: 'A delivery driver joined the pub quiz between drops. MVP.' },
  { k: 'funny', t: 'The fire blanket has never been used. Unlike the sarcasm blanket.' },
  { k: 'funny', t: 'Someone asked if dogs get a loyalty card. We’re considering it.' },
  { k: 'funny', t: 'We staged a soft close. Hard close arrived anyway.' },
  { k: 'funny', t: 'A guest left a five-star review for the gravy alone. Priorities.' },
  { k: 'funny', t: 'The coat check is a hook and a prayer.' },
  { k: 'funny', t: 'Someone requested “background jazz.” We had background dishwasher.' },
  { k: 'funny', t: 'We found three lighters and zero pens. Universal constant.' },
  { k: 'funny', t: 'A booking for “intimate” became a surprise party. Intimacy redefined.' },
  { k: 'funny', t: 'The till drawer stuck. We opened it with lore and leverage.' },
  { k: 'funny', t: 'Someone asked for sparkling water “but flat.” We poured still with sparkle eyes.' },
  { k: 'funny', t: 'We trained on upselling. Upsold ourselves a break. Failed.' },
  { k: 'funny', t: 'Someone brought sheet music. Karaoke night declared itself.' },
  { k: 'funny', t: 'The beer lines got a deep clean. Staff got a deep sigh of relief.' },
  { k: 'funny', t: 'Someone tipped the quiz machine. The machine did not tip back.' },
  { k: 'funny', t: 'We put “wet floor” signs everywhere. Guests still found the wet floor.' },
  { k: 'funny', t: 'A regular’s usual changed. Identity crisis averted with a tasting flight.' },
  { k: 'funny', t: 'The garden heater remote vanished. Remote working, we assume.' },
  { k: 'funny', t: 'Someone asked for the wine list “without numbers.” Chaos pricing.' },
  { k: 'funny', t: 'We hosted a baby shower. The soft play was accidental.' },
  { k: 'funny', t: 'A guest photographed every plate. The chips felt famous.' },
  { k: 'funny', t: 'The staff WhatsApp is 40% memes, 60% “who’s on starters?”' },
  { k: 'funny', t: 'Someone reserved the snug for a board meeting. Snug approved the minutes.' },
  { k: 'funny', t: 'We ran a curry night. The extractor fan filed for overtime.' },
  { k: 'funny', t: 'A lost phone rang from the lost box. Poetry.' },
  { k: 'funny', t: 'Someone asked whether the pie was “emotionally available.” It was.' },
  { k: 'funny', t: 'We found a single glove every week for a month. Pair still missing.' },
  { k: 'funny', t: 'A guest brought binoculars for the specials board. Fair.' },
  { k: 'funny', t: 'The patio heater remote reappeared in the sugar tin. Full circle.' },
  { k: 'funny', t: 'Someone booked “a corner for plotting.” We provided snacks and deniability.' },
  { k: 'funny', t: 'We ran out of mayonnaise. Diplomacy switched to aioli.' },
  { k: 'funny', t: 'A hen party named every cocktail after an ex. Menu trauma.' },
  { k: 'funny', t: 'Someone asked for the bill in iambic pentameter. We declined in prose.' },
  { k: 'funny', t: 'The glasswasher paused mid-cycle to think. Relatable.' },
  { k: 'funny', t: 'A guest left a thank-you note for the ice. Scarcity appreciation.' },
  { k: 'funny', t: 'We hosted twin birthdays same night. Cake logistics: advanced.' },
  { k: 'funny', t: 'Someone tried to reserve the dartboard. We offered a table and dignity.' },
  { k: 'funny', t: 'The cellar torch died mid-stocktake. Plot twist lighting.' },
  { k: 'funny', t: 'A regular’s dog refused the dog biscuit. Critic in residence.' },
  { k: 'funny', t: 'We put “no phones on speaker” on a card. Speakerphones increased. Irony.' },
  { k: 'funny', t: 'Someone asked for the wine “with the funniest label.” Merchandising won.' },
  { k: 'funny', t: 'The soft-serve machine had a hard day. Metaphor complete.' },
  { k: 'funny', t: 'A booking note said “bring your own cake.” They brought three. Escalation.' },
  { k: 'funny', t: 'We found a calculator in lost property. Float check called dibs.' },
  { k: 'funny', t: 'Someone ordered a round for “whoever looks tired.” Whole shift cheered.' },
  { k: 'funny', t: 'The umbrella farm by the door elected a leader. Black, slightly broken.' },
  { k: 'funny', t: 'A guest asked if we do quiet discos. We do quiet dishwashers. Close.' },
  { k: 'funny', t: 'We labelled the clean and dirty zones. Guests invented a third zone.' },
  { k: 'funny', t: 'Someone reserved two tables “for options.” Schrödinger’s seating.' },
  { k: 'funny', t: 'The piano received one competent song then chaos. Peak open mic.' },
  { k: 'funny', t: 'A delivery of lemons arrived as limes. Cocktail menu adapted emotionally.' },
  { k: 'funny', t: 'We hosted a retirement and a hen do same lunch. Tone: advanced.' },
  { k: 'funny', t: 'Someone asked for the manager and got a trainee’s confidence. Growth.' },
  { k: 'funny', t: 'The ice well rubber duck was promoted to shift mascot. Unofficial.' },
  { k: 'funny', t: 'A guest tipped in bus tickets. Journey complete.' },
  { k: 'funny', t: 'We found the missing pen inside the till. Homecoming.' },
  { k: 'funny', t: 'Someone asked if the gravy could be “less gravy.” Philosophical.' },
  { k: 'funny', t: 'The quiz machine’s top score is held by a delivery driver. Legend.' },
  { k: 'funny', t: 'A booking for “just coffee” lasted through lunch. Soft launch longevity.' },
  { k: 'funny', t: 'We ran a steak night. The extractor fan unionised in spirit.' },
  { k: 'funny', t: 'Someone left a five-star review for the coat hooks. Priorities clarified.' },
  { k: 'funny', t: 'The Christmas lights blinked in Morse. We ignored the overtime message.' },
  { k: 'funny', t: 'A guest brought a portable charger and a subplot. Power user.' },
  { k: 'funny', t: 'We put flowers back after the dog incident. Hope blooms.' },
  { k: 'funny', t: 'Someone asked for “the table farthest from destiny.” Assigned mid-room.' },
  { k: 'funny', t: 'The cellar map led to a mop. Adventure complete.' },
  { k: 'funny', t: 'A regular corrected our grammar and our bitter pour. Double consultant.' },
  { k: 'funny', t: 'We hosted a silent book club. Pages turned; pints louder.' },
  { k: 'funny', t: 'Someone tried to pay with foreign coins and a smile. Smile accepted.' },
  { k: 'funny', t: 'The patio cushions returned outside. Seasonal migration complete.' },
  { k: 'funny', t: 'A guest asked for the meaning of the specials. We said “survival.”' },
  { k: 'funny', t: 'We found another monocle. Trend emerging.' },
  { k: 'funny', t: 'Someone reserved under a fake name then forgot it. Spy failed.' },
  { k: 'funny', t: 'The glasswasher’s high C returned for an encore. Unwanted.' },
  { k: 'funny', t: 'A hen do sash was left behind. Landlord wore it again. Continuity.' },
  { k: 'funny', t: 'We ran out of tonic twice. Soft drinks invented themselves.' },
  { k: 'funny', t: 'Someone asked if the fireplace takes bookings. Emotionally fully booked.' },
  { k: 'funny', t: 'The staff meal was soup again. Universe consistent.' },
  { k: 'funny', t: 'A guest left binoculars. Specials board felt watched.' },
  { k: 'funny', t: 'We labelled “HOT” hotter. Guests still asked. Persistence.' },
  { k: 'funny', t: 'Someone booked the snug for “strategy and chips.” Approved.' },
  { k: 'funny', t: 'The lost phone rang during last orders. Dramatic timing.' },
  { k: 'funny', t: 'A quiz team called “Experts” finished seventh. Humility DLC.' },
  { k: 'funny', t: 'We found the heater remote in the sugar tin again. Haunted.' },
  { k: 'funny', t: 'Someone asked for sparkling still water. We poured poetry.' },
  { k: 'funny', t: 'The coat hooks achieved maximum density Friday. Physics demo.' },
  { k: 'funny', t: 'A guest tipped the kitchen in cake. Morale critical hit.' },
  { k: 'funny', t: 'We put “wait to be seated” in larger font. Guests still self-seated.' },
  { k: 'funny', t: 'Someone brought measuring tape for the burger again. Sequel science.' },
  { k: 'funny', t: 'The rubber duck attended the leadership meeting. Quorum.' },
  { k: 'funny', t: 'A booking note: “allergic to waiting.” Untreatable; seated fast.' },
  { k: 'funny', t: 'We hosted karaoke after a wake. Emotional range: expert.' },
  { k: 'funny', t: 'Someone ordered one of everything small again. Kitchen déjà vu.' },
  { k: 'funny', t: 'The love-letter complaint menu sequel arrived. Franchise.' },
  { k: 'funny', t: 'A guest rated the dog bowl and the gravy. Consistent critic.' },
  { k: 'funny', t: 'We found zero pens and four lighters. Constant holds.' },
  { k: 'funny', t: 'Someone asked for jazz and got dishwasher. Genre bend.' },
  { k: 'funny', t: 'The soft close became a hard close with soft hearts.' },
  { k: 'funny', t: 'A regular’s dog earned an unofficial loyalty stamp. Pilot programme.' },
  { k: 'funny', t: 'We ran curry night; extractor fan filed overtime again. Precedent.' },
  { k: 'funny', t: 'Someone left sheet music and confidence. Karaoke sequels incoming.' },
  { k: 'funny', t: 'The till lore-and-leverage trick entered staff training. Oral history.' },
  { k: 'true', t: 'True: CAMRA — the Campaign for Real Ale — was founded in 1971 by four beer fans who wanted better pints.' },
  { k: 'true', t: 'True: a “tied house” buys beer from a set brewery or pubco; a “free house” can choose its own lines.' },
  { k: 'true', t: 'Pub fact: “last orders” and the closing bell grew from wartime licensing rules that stuck for decades.' },
  { k: 'true', t: 'True: the Licensing Act 2003 scrapped fixed national closing times — pubs apply for their own hours.' },
  { k: 'true', t: 'Surprising: before 1914, many British pubs had far looser hours; WWI made “time!” feel like natural law.' },
  { k: 'true', t: 'True: don’t ring the bar bell yourself — that’s traditionally staff kit for last orders, not a service bell.' },
  { k: 'true', t: 'Pub etiquette: there’s often an invisible queue at the bar — eye contact beats finger-snapping.' },
  { k: 'true', t: 'True: buying rounds is a social contract. Skipping your turn is remembered longer than the drinks.' },
  { k: 'true', t: 'Odd fact: Roman Britain had tabernae (wine shops) along roads — early pit-stops before “pubs” existed.' },
  { k: 'true', t: 'True: hops turned English “ale” into hopped “beer” over the late Middle Ages; the names later blurred.' },
  { k: 'true', t: 'Surprising: by 1577 England and Wales had roughly 17,000 alehouses — denser than modern pub maps.' },
  { k: 'true', t: 'True: alehouse licensing in England dates to an Act of 1552 — paperwork is older than your POS.' },
  { k: 'true', t: 'Pub history: coaching inns timed changeovers with bells — hospitality logistics before spreadsheets.' },
  { k: 'true', t: 'True: Victorian pubs went big on etched glass, tiles, and mirrors — showroom drinking for the industrial city.' },
  { k: 'true', t: 'Surprising: snugs often charged more for beer — privacy had a premium, frosted glass included.' },
  { k: 'true', t: 'True: ladies, clergy, and coppers sometimes preferred the snug when the public bar felt too public.' },
  { k: 'true', t: 'Odd fact: the ploughman’s name was boosted by 1950s–60s cheese marketing — bread, cheese, pickles, story.' },
  { k: 'true', t: 'True: Milk Marketing Board showcards helped put “ploughman’s lunch” on pub bars nationwide.' },
  { k: 'true', t: 'Surprising: bread-and-cheese-with-beer is ancient; the branded “ploughman’s” plate is much newer.' },
  { k: 'true', t: 'True: “Time, gentlemen, please!” marked the end of service — even when ladies were clearly present.' },
  { k: 'true', t: 'Pub fact: after last orders you traditionally got drinking-up time — finish, don’t reorder.' },
  { k: 'true', t: 'True: coffee houses in Georgian London were nicknamed penny universities — news, deals, and caffeine.' },
  { k: 'true', t: 'Surprising: ice for drinks was once a luxury trade — block ice shipped before everyday freezers.' },
  { k: 'true', t: 'True: monastery breweries kept beer knowledge alive across medieval Europe — monks as early head brewers.' },
  { k: 'true', t: 'Odd fact: a yard of ale is a tall, awkward glass — more party trick than efficient vessel.' },
  { k: 'true', t: 'True: “86” for “we’re out” is US kitchen slang that hopped the Atlantic with the rest of the chaos.' },
  { k: 'true', t: 'Surprising: restaurant comes from French restaurer — to restore — originally restorative broths, not steaks.' },
  { k: 'true', t: 'True: oyster bars were once cheap late-night fuel; scarcity and fashion flipped them into luxury.' },
  { k: 'true', t: 'Pub lore: pewter pots and marked measures were part of the fight against short-measure landlords.' },
  { k: 'true', t: 'True: public bar vs lounge/saloon often meant different prices and different vibes under one roof.' },
  { k: 'true', t: 'Surprising: some inns ran singing licences — karaoke’s Victorian great-grandparent, with paperwork.' },
  { k: 'true', t: 'True: table service at the bar is not the UK default — order up front unless it’s a dining room.' },
  { k: 'true', t: 'Odd fact: “mine host” for the landlord is old pub English — hospitality with a theatrical bow.' },
  { k: 'true', t: 'True: free houses can still be mortgaged to a brewery — “free” isn’t always free of ties.' },
  { k: 'true', t: 'Surprising: guest-beer rights for some tied pubs were a later legal tweak to widen choice.' },
  { k: 'true', t: 'True: CAMRA’s early articles already cared about traditional pub facilities — not just the beer.' },
  { k: 'true', t: 'Pub fact: classic unaltered snugs are rare now — CAMRA tracks historic interiors so they aren’t ripped out.' },
  { k: 'true', t: 'True: “bar” may nod to the barrier that secured stock — a trust issue with a wooden solution.' },
  { k: 'true', t: 'Surprising: blackout wartime pubs meant quieter nights — less light, same gossip throughput.' },
  { k: 'true', t: 'True: stagecoach inns sold beds and beer — Airbnb with horses and worse reviews.' },
  { k: 'true', t: 'Odd fact: “last orders” as a scramble culture outlived the law that created the scramble.' },
  { k: 'true', t: 'True: tipping as a word comes from old slang “to give,” not from a box labelled T.I.P.' },
  { k: 'true', t: 'Surprising: early tip culture in Britain was often for servants and porters — pubs weren’t always tip jars.' },
  { k: 'true', t: 'True: many pubs still call last orders out of habit even with flexible modern licences.' },
  { k: 'true', t: 'Pub etiquette: the polite bar wave is often an eyebrow-raise and chin-nod — subtle pantomime.' },
  { k: 'true', t: 'True: 1988 finally let English pubs open through the afternoon again after decades of split sessions.' },
  { k: 'true', t: 'Surprising: Sunday hours were tighter than weekday hours for years — roast timing with legal drama.' },
  { k: 'true', t: 'True: inns, taverns, and alehouses were once distinct — beds, wine, and everyday ale, respectively.' },
  { k: 'true', t: 'Odd fact: “public house” shortened to “pub” — branding by exhaustion.' },
  { k: 'true', t: 'True: etched pub mirrors weren’t just pretty — they bounced light in gaslit rooms.' },
  { k: 'true', t: 'Surprising: some historic pubs still keep rare pewter bar tops — soft metal, hard to replace.' },
  { k: 'true', t: 'True: porter and stout grew with industrial London — big beer for big cities.' },
  { k: 'true', t: 'Pub fact: a managed house has a salaried manager; a tenancy rents the business from the pubco.' },
  { k: 'true', t: 'True: “empty your glasses, please” is the soft landing after “time” — hospitality’s least popular lullaby.' },
  { k: 'true', t: 'Surprising: before hops, British ale was unhopped; hopped beer arrived as a continental idea.' },
  { k: 'true', t: 'True: quiz nights and darts leagues are modern social glue — same room, different scoreboard.' },
  { k: 'true', t: 'Odd fact: some pubs once had separate entrances for different classes of traveller.' },
  { k: 'true', t: 'True: “lounge” historically meant sit-down comfort; “bar” meant stand-up drinking — lines blur now.' },
  { k: 'true', t: 'Surprising: the Defence of the Realm Act in WWI tightened drink hours for munitions workers — and stuck.' },
  { k: 'true', t: 'True: “drinking-up time” used to be written into law; now it’s mostly licence wording and landlord call.' },
  { k: 'true', t: 'True: “Time, please!” still lands even when the licence could run later — culture beats statute.' },
  { k: 'true', t: 'Surprising: many historic pub interiors are listed or CAMRA-logged so refurbishments don’t erase them.' },
  { k: 'true', t: 'True: rounds culture is stronger in the UK than table-tab culture in many other countries.' },
  { k: 'true', t: 'Odd fact: some Victorian pubs had separate “jug and bottle” hatches for take-home beer.' },
  { k: 'true', t: 'True: etched glass and frosted partitions let pubs feel private without needing full walls.' },
  { k: 'true', t: 'Surprising: the word “alehouse” stuck long after hopped beer became normal — branding inertia.' },
  { k: 'true', t: 'True: railway refreshment rooms once competed with pubs for travellers’ thirst.' },
  { k: 'true', t: 'Pub fact: a “lock-in” after hours is folklore and risk — licences still rule the night.' },
  { k: 'true', t: 'True: pewter softens and dents — historic pewter bar tops are maintenance with a museum vibe.' },
  { k: 'true', t: 'Surprising: some pubs display historic measures as décor — metrology as interior design.' },
  { k: 'true', t: 'True: “half and half” mixes (like stout and ale) have local names and fierce opinions.' },
  { k: 'true', t: 'Odd fact: early coffee-house culture incubated insurance and newspapers — caffeine as infrastructure.' },
  { k: 'true', t: 'True: guest ales and changing cask clips are part of free-house theatre.' },
  { k: 'true', t: 'Surprising: some coaching inns kept ostlers — the original “valet parking,” but with horses.' },
  { k: 'true', t: 'True: “mine host” and “landlord” both stuck; “publican” is the formal job title with tax vibes.' },
  { k: 'true', t: 'Pub fact: quiet rooms and family rooms were later social inventions — pubs kept reinventing space.' },
  { k: 'true', t: 'True: beer gardens grew with smoking bans and summer optimism — outdoors as overflow dining room.' },
  { k: 'true', t: 'Surprising: some licences still spell out exactly when alcohol sales must stop — read the small print.' },
  { k: 'true', t: 'True: CAMRA’s Good Beer Guide helped turn real ale hunting into a national hobby.' },
  { k: 'true', t: 'Odd fact: pub names often encode forgotten trades, saints, or royal propaganda on a signboard.' },
  { k: 'true', t: 'True: a painted pub sign was literacy for travellers who couldn’t read the letters underneath.' },
  { k: 'true', t: 'Surprising: “Inn” in a name once promised lodging; many inns no longer do beds — name stickiness.' },
  { k: 'true', t: 'True: spit-and-sawdust floors are mostly nostalgia now — health inspectors prefer mopped reality.' },
  { k: 'true', t: 'Pub fact: darts, dominoes, and crib were the original engagement metrics.' },
  { k: 'true', t: 'True: some historic pubs claim “oldest” status — historians argue, landlords smile for the camera.' },
  { k: 'true', t: 'Surprising: cellar temperature control is half the pint — lines and kegs are the other half.' },
  { k: 'true', t: 'True: cask ale needs careful venting and settling — living beer with a shift rota of its own.' },
  { k: 'true', t: 'Odd fact: “firkins” and “kilderkins” are cask sizes — vocabulary that survives stocktake day.' },
  { k: 'true', t: 'True: a clean glass and a correct temperature fix more “off” beer complaints than speeches do.' },
  { k: 'true', t: 'Surprising: some pubs still ring a real brass bell for last orders — theatre with legal roots.' },
  { k: 'true', t: 'True: “one for the road” used to mean a last drink before travelling — now it means negotiate a taxi.' },
  { k: 'true', t: 'Pub fact: wet-led pubs lean on drink sales; food-led pubs lean on the kitchen — different heartbeats.' },
  { k: 'true', t: 'True: Sunday lunch as a pub ritual outlived the strict Sunday session laws that shaped it.' },
  { k: 'true', t: 'Surprising: some inns posted mail and horses — logistics hubs before the parcel locker.' },
  { k: 'true', t: 'True: frosted snug glass let you hear the bar without being seen — privacy tech, Victorian edition.' },
  { k: 'true', t: 'Odd fact: “snug” prices could be higher even for the same beer — ambience as a SKU.' },
  { k: 'true', t: 'True: free-of-tie leases still come with rent and terms — freedom with invoices.' },
  { k: 'true', t: 'Surprising: wartime blackout curtains made pubs darker and conversations closer.' },
  { k: 'true', t: 'True: the 2005 flexible hours wave didn’t erase last-orders energy — habits are sticky.' },
  { k: 'true', t: 'Pub fact: eye contact at the bar is the polite “I’m next” signal across much of Britain.' },
  { k: 'true', t: 'True: bringing your empty glass back is kindness, not obligation — staff still appreciate it.' },
  { k: 'true', t: 'Surprising: some historic pubs kept separate taprooms for market-day chaos vs parlour calm.' },
  { k: 'true', t: 'True: “Real ale” in CAMRA terms means cask-conditioned beer — living product, not a vibe word only.' },
  { k: 'true', t: 'Odd fact: pub quizzes boomed as cheap midweek theatre — trivia as yield management.' },
  { k: 'true', t: 'True: a good cellar book beats a good excuse when the pint tastes wrong.' },
  { k: 'true', t: 'Surprising: hops add bitterness and help preservation — flavour with a shelf-life subplot.' },
  { k: 'true', t: 'True: many “ancient” pub beams are theatre; the licence history is the real archaeology.' },
  { k: 'true', t: 'Pub fact: takeaway pints in jugs were normal long before craft cans — refill culture 1.0.' },
  { k: 'true', t: 'True: “Time, gentlemen” outlasted the gender mix — language lagged the room.' },
  { k: 'true', t: 'Surprising: some councils still get noise complaints about pubs with singing — tradition vs neighbours.' },
  { k: 'true', t: 'True: pub signs were once practical wayfinding — a picture you could spot before you could read.' },
  { k: 'true', t: 'Surprising: some historic pubs keep a “history shelf” of old bottles and measures as soft museum.' },
  { k: 'true', t: 'True: cask beer is still living when it hits the glass — temperature and line cleanliness matter.' },
  { k: 'true', t: 'Odd fact: “one over the eight” is old slang for tipsy — military counting with consequences.' },
  { k: 'true', t: 'True: many villages still treat the pub as the unofficial noticeboard and soft town hall.' },
  { k: 'true', t: 'Surprising: some licences require specific door staff numbers — hospitality with a security subplot.' },
  { k: 'true', t: 'True: “wet led” vs “food led” changes everything from rota shape to glasswash rhythm.' },
  { k: 'true', t: 'Pub fact: a good landlord reads the room faster than any sensor.' },
  { k: 'true', t: 'True: froth and head on a pint are partly theatre, partly release of aroma — foam with a job.' },
  { k: 'true', t: 'Surprising: some pubs still sell pickled eggs at the bar — snack continuum unbroken.' },
  { k: 'true', t: 'True: “lock-in” stories outnumber actual legal lock-ins — folklore is generous.' },
  { k: 'true', t: 'Odd fact: the phrase “mine host” shows up in older literature as the friendly face of the house.' },
  { k: 'true', t: 'True: beer gardens boom when the sun appears for twelve minutes — British yield management.' },
  { k: 'true', t: 'Surprising: cellar cooling failures show up in the glass before they show up on a dashboard.' },
  { k: 'true', t: 'True: CAMRA local branches still fight pub closures and poor refurbishments — activism with a pint.' },
  { k: 'true', t: 'Pub fact: a clean line and a patient pull beat most “craft” marketing claims.' },
  { k: 'true', t: 'True: “half of lager and a packet of crisps” remains a valid British business lunch in some postcodes.' },
  { k: 'true', t: 'Surprising: some historic interiors hide rare bar engines and spirit rails — machinery as décor.' },
  { k: 'true', t: 'True: guest beers rotate so regulars have something to argue about — engagement by cask clip.' },
  { k: 'true', t: 'Odd fact: “snug” survives in pub architecture talk long after many snugs were knocked through.' },
  { k: 'true', t: 'True: Sunday trading and Sunday licensing were different fights — shops and pints, separate sagas.' },
  { k: 'true', t: 'Surprising: some pubs were built as “improved public houses” to civilise drinking with food and light.' },
  { k: 'true', t: 'True: a chalked specials board is still faster UX than most apps — dry-wipe agility.' },
  { k: 'true', t: 'Pub fact: eye contact and a half-step forward beat waving a tenner at the bar.' },
  { k: 'true', t: 'True: “last orders” energy persists because humans love a countdown more than a flexible licence.' },
  { k: 'true', t: 'Surprising: some pubs kept a separate off-sales counter long after supermarket beer arrived.' },
  { k: 'true', t: 'True: measure marks on glassware are part of trading-standards theatre every busy Friday.' },
  { k: 'true', t: 'Odd fact: “landlord” once literally meant land holder — hospitality with a property subplot.' },
  { k: 'true', t: 'True: cask clips are tiny billboards — design department meets cellar person.' },
  { k: 'true', t: 'Surprising: many “gaslit” vibes today are LED nostalgia with better fire safety.' },
  { k: 'true', t: 'True: a well-kept cellar diary is underrated management software.' },
  { k: 'true', t: 'Pub fact: dogs in pubs are a culture war settled table by table — usually in the dog’s favour.' },
  { k: 'true', t: 'True: “Time!” can be a shout, a bell, or a look — multilingual closing energy.' },
  { k: 'true', t: 'Surprising: some historic pubs survive as community shares — locals buying the soft town hall.' },
  { k: 'true', t: 'True: line cleaning schedules are romance for cellar folk and salvation for drinkers.' },
  { k: 'true', t: 'Odd fact: “beer engine” sounds steampunk and often is — handpull mechanics with theatre.' },
  { k: 'true', t: 'True: guest night menus and quiz themes are yield tools wearing entertainment costumes.' },
  { k: 'true', t: 'Surprising: frosted glass snugs were social technology before open-plan everything.' },
  { k: 'true', t: 'True: a patient pull on cask beats a rushed one — foam management as craft.' },
  { k: 'true', t: 'Pub fact: the best free houses still curate like record shops — stock with a point of view.' },
  { k: 'true', t: 'True: “last orders” remains useful even with late licences — soft landing for the room.' },
  { k: 'true', t: 'Surprising: some inns advertised hot water and stabling harder than the beer — priorities of travel.' },
  { k: 'true', t: 'True: pewter and silver tankards once signalled status — your vessel was part of the costume.' },
  { k: 'true', t: 'Odd fact: “ale-conner” officials once tested beer quality — early QA with civic theatre.' },
  { k: 'true', t: 'True: modern allergens boards are the descendant of “trust the cook” — paperwork with care.' },
  { k: 'true', t: 'Surprising: many pub gardens were afterthoughts that became the main event in heatwaves.' },
  { k: 'true', t: 'True: a clean line, clean glass, and correct temp solve most “this pint’s off” mysteries.' },
  { k: 'true', t: 'Pub fact: CAMRA’s interior listings are why some etched glass still survives the refurb urge.' },
  { k: 'true', t: 'True: rounds are informal credit — social ledger without a POS.' },
  { k: 'true', t: 'Surprising: some licences still mention “drinking up” windows even after national hours vanished.' },
  { k: 'true', t: 'True: the snug’s privacy premium was an early version of “experience pricing.”' },
  { k: 'true', t: 'Odd fact: “publican” shares roots with tax farming history — the job title carries ledger energy.' },
  { k: 'true', t: 'True: hand-pulled ale is theatre and engineering — optics with a sparkler debate.' },
  { k: 'true', t: 'Surprising: village pubs doubling as post offices or shops are soft infrastructure in disguise.' },
  { k: 'true', t: 'True: “Time, please” works because everyone pretends they didn’t hear it the first time.' },
];

function hospitalityYarnKindLabel_(k) {
  if (k === 'true') return 'True-ish';
  if (k === 'funny') return 'Shift yarn';
  return 'Quick one';
}

/** Built-in + Script Property extras (deduped by text). */
function getHospitalityYarnBank_() {
  var list = (HOSPITALITY_YARNS_ || []).slice();
  try {
    var raw = PropertiesService.getScriptProperties().getProperty('HOSPITALITY_YARNS_EXTRA');
    if (raw) {
      var extra = JSON.parse(raw);
      if (extra && extra.length) {
        var seen = {};
        for (var i = 0; i < list.length; i++) seen[String(list[i].t || '')] = true;
        for (var j = 0; j < extra.length; j++) {
          var item = extra[j];
          if (!item || !item.t) continue;
          var key = String(item.t);
          if (seen[key]) continue;
          seen[key] = true;
          list.push({ k: item.k || 'joke', t: key });
        }
      }
    }
  } catch (e) {
    Logger.log('getHospitalityYarnBank_ extras: ' + e);
  }
  return list;
}

/**
 * Stable pick for a calendar day. Year shifts the sequence so the same
 * calendar date next year does not replay the same yarn.
 */
function getHospitalityYarnForDate_(date) {
  var list = getHospitalityYarnBank_();
  if (!list || !list.length) {
    return { kind: 'joke', label: 'Quick one', text: 'Service with a smile — teeth optional after midnight.' };
  }
  var d = date instanceof Date ? date : new Date();
  var start = new Date(d.getFullYear(), 0, 0);
  var dayOfYear = Math.floor((d - start) / 86400000);
  var seed = d.getFullYear() * 400 + dayOfYear;
  var idx = ((seed % list.length) + list.length) % list.length;
  var yarn = list[idx];
  return {
    kind: yarn.k,
    label: hospitalityYarnKindLabel_(yarn.k),
    text: yarn.t,
    index: idx,
    bankSize: list.length
  };
}

/** Public for diagnostics / clasp run. */
function getHospitalityYarnToday() {
  return getHospitalityYarnForDate_(new Date());
}

/**
 * Append yarns to Script Properties extras (no code redeploy needed for content).
 * @param {Array<{k?:string,t:string}>} yarns
 */
function appendHospitalityYarns(yarns) {
  if (!yarns || !yarns.length) return { success: false, message: 'No yarns provided' };
  var props = PropertiesService.getScriptProperties();
  var existing = [];
  try {
    var raw = props.getProperty('HOSPITALITY_YARNS_EXTRA');
    if (raw) existing = JSON.parse(raw) || [];
  } catch (e1) {
    existing = [];
  }
  var seen = {};
  for (var i = 0; i < existing.length; i++) seen[String(existing[i].t || '')] = true;
  var added = 0;
  for (var j = 0; j < yarns.length; j++) {
    var y = yarns[j];
    if (!y || !y.t) continue;
    var t = String(y.t).trim();
    if (!t || seen[t]) continue;
    seen[t] = true;
    existing.push({ k: y.k || 'joke', t: t });
    added++;
  }
  props.setProperty('HOSPITALITY_YARNS_EXTRA', JSON.stringify(existing));
  return {
    success: true,
    added: added,
    extraTotal: existing.length,
    bankTotal: getHospitalityYarnBank_().length
  };
}
